version: '3.8'
services:
  # MySQL for springboot
  mysql_springboot:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - mysql_springboot_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # PhpMyAdmin for springboot MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_springboot:mysql
    ports:
      - 8889:80
    environment:
      PMA_HOST: mysql_springboot
      PMA_PORT: 3306
    networks:
      - my_network

volumes:
  mysql_springboot_data:

networks:
  my_network:
    driver: bridge
