version: '3.8'
services:
  # MySQL for springboot
  mysql_springboot:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - mysql_springboot_data:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # MySQL for Keycloak
  mysql_keycloak:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - 3307:3306 # Expose on a different port to avoid conflict
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  # PhpMyAdmin for springboot MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql_springboot:mysql
    ports:
      - 8889:80
    environment:
      PMA_HOST: mysql_springboot
      PMA_PORT: 3306
    networks:
      - my_network

  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:16.0.0
    ports:
      - 8443:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql_keycloak
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_HTTP_ENABLED=true
      - KEYCLOAK_HTTPS_ENABLED=false
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - mysql_keycloak
    networks:
      - my_network

  springboot:
    build: .
    image: lakosalexx/officerbackend:v1.0
    environment:
      - ACCESS_TOKEN_KEY=access_token
      - AUTH_ADMIN_CLIENT_ID=admin-cli
      - AUTH_ADMIN_CLIENT_PASSWORD=admin
      - AUTH_ADMIN_CLIENT_USERNAME=admin
      - AUTH_BASE_URL=http://vps-5884ed77.vps.ovh.net:8443/auth/
      - AUTH_CLIENT_ID=officer-client
      - AUTH_REALM_NAME_OR_TENANT_ID=Officer
      - AUTH_SERVICE_NAME=keycloak
      - REFRESH_TOKEN_KEY=refresh_token
      - SESSION_ID_KEY=JSESSIONID
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_springboot:3306/test_db
      - SPRING_DATASOURCE_USERNAME=root
    depends_on:
      - mysql_springboot
      - keycloak
    network_mode: host 
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      retries: 20
      start_period: 5s
      timeout: 10s
    restart: on-failure

volumes:
  mysql_springboot_data:
  mysql_keycloak_data:


networks:
  my_network:
    driver: bridge
